.TH man 1 "16 May 2020" "0.3.2" "git-mirror-auto man page"
.SH NAME
git-mirror-auto \- automatic updater for git-mirror
.SH SYNOPSIS
.B git-mirror-auto
[path]
.PP
Batch updates all subdirectories.
.SH ARGUMENTS
.B path
\- path to check for batch updating subdirectories
.PP
.SH AUTHOR
Jan Baudisch (jan@baudisch.xyz)
